import type { Metadata } from "next";
import "./globals.css";
// import { Yuji_Mai, Poppins } from "next/font/google";

// const yujiMai = Yuji_Mai({
//   variable: "--font-Yuji_Mai",
//   subsets: ["latin"],
//   weight: "400",
// });

// const poppins = Poppins({
//   variable: "--font-Poppins",
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700", "800"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // ${yujiMai.variable} ${poppins.variable}

    <html lang="en">
      <body
        className={`
           antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
